### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by SodiumBenjahmin420** [OssieNomae/Blueprint#1]
Attempt to use a closed document
 
 Script 'cloud_16867958047.Blueprint.Blueprint', Line 150
 
 error occurs like this:
 
 Open blueprint > Any script type blueprint
 
 Edit the script > Close it
 
 Throws the error, doesnt delete the "Temporary Instance" and upon creating a script that **should** have a blueprint, it just defaults to its script-types default innards ( print("Hello World!"), local Module = {} return Module)

**Comment by OssieNomae** [comment]
This is most likely an issue when using team create, oversight on my part.

Should be fixed with 1.2.1 now.
